default:
  interruptible: true
  timeout: 30 minutes

stages:
  - commit
  - acceptance
  - deploy
  - cleanup

.assume_role: &assume_role
  - >
    STS=($(aws sts assume-role-with-web-identity
    --role-arn ${AWS_ROLE_ARN}
    --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
    --web-identity-token $ID_TOKEN
    --duration-seconds 3600
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
    --output text))
  - export AWS_ACCESS_KEY_ID="${STS[0]}"
  - export AWS_SECRET_ACCESS_KEY="${STS[1]}"
  - export AWS_SESSION_TOKEN="${STS[2]}"

.build_containers: &build_containers
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: commit
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

CLIENT_UNIT_TEST:
  image: node:20-alpine
  stage: commit
  script:
    - cd client-vite
    - npm install
    - CI=true npm test

CLIENT_BUILD:
  image: node:20-alpine
  stage: commit
  script:
    - cd client-vite
    - npm install
    - npm run build
  artifacts:
    paths:
      - client-vite/dist
    when: on_success

CLIENT_BUILD_CONTAINER:
  <<: *build_containers
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/client:$CI_COMMIT_SHORT_SHA
  before_script:
    - cd client-vite

CLIENT_DEPLOY_STAGING:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  id_tokens:
    ID_TOKEN:
      aud: habit_kicker_react_s3
  stage: acceptance
  script:
    - *assume_role
    - aws s3 sync client-vite/dist s3://${S3_BUCKET}/staging
    - aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths "/index.html"

CLIENT_DEPLOY_PRODUCTION:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  id_tokens:
    ID_TOKEN:
      aud: habit_kicker_react_s3
  stage: deploy
  when: manual
  script:
    - *assume_role
    - aws s3 sync client-vite/dist s3://${S3_BUCKET}/production
    - aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths "/index.html"

API_BUILD:
  <<: *build_containers
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA
  before_script:
    - cd habit-kicker-rails

NGINX_BUILD:
  <<: *build_containers
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHORT_SHA
  before_script:
    - cd nginx

CLEANUP_CI_DOCKER_IMAGES:
  image: curlimages/curl:7.86.0
  stage: cleanup
  variables:
    REG_SHA256: ade837fc5224acd8c34732bf54a94f579b47851cc6a7fd5899a98386b782e228
    REG_VERSION: 0.16.1
  before_script:
    - curl --fail --show-error --location "https://github.com/genuinetools/reg/releases/download/v$REG_VERSION/reg-linux-amd64" --output ./reg
    - echo "$REG_SHA256  ./reg" | sha256sum -c -
    - chmod a+x ./reg
  script:
    - ./reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA
    - ./reg rm -d --auth-url $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE/client:$CI_COMMIT_SHORT_SHA
  when: always

#CYPRESS:
#  stage: acceptance
#  image: cypress/browsers:node18.12.0-chrome107
#  variables:
#    DATABASE_URL: postgres:postgres//postgres:postgres_password@postgres:5432
#    POSTGRES_PASSWORD: postgres_password
#  services:
#    - $CI_REGISTRY_IMAGE/api:$CI_COMMIT_SHORT_SHA
#    - $CI_REGISTRY_IMAGE/client:$CI_COMMIT_SHORT_SHA
#    - postgres
#    - name: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_SHORT_SHA
#      command: ["rails", "db:setup", "&&", "rails", "server", "-b", "0.0.0.0", "-p", "5000"]
#  script:
#    - echo hello cypress
