default:
  interruptible: true
  timeout: 30 minutes

stages:
  - commit
  - acceptance

.client_setup: &client_setup
  image: node:20-alpine
  before_script:
    - cd hk_client
    - npm i

ASSUME_ROLE:
  stage: commit
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  id_tokens:
    ID_TOKEN:
      aud: habit_kicker_react_s3
  script:
    - >
      STS=($(aws sts assume-role-with-web-identity
      --role-arn ${AWS_ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $ID_TOKEN
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - echo AWS_ACCESS_KEY_ID="${STS[0]}" >> build.env
    - echo AWS_SECRET_ACCESS_KEY="${STS[1]}" >> build.env
    - echo AWS_SESSION_TOKEN="${STS[2]}" >> build.env
  artifacts:
    reports:
      dotenv: build.env

CLIENT_LINT:
  <<: *client_setup
  stage: commit
  script:
    - npm run lint

CLIENT__BUILD:
  <<: *client_setup
  stage: commit
  script:
    - npm run build
  artifacts:
    paths:
      - hk_client/dist

CLIENT__DEPLOY_STAGING:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  stage: acceptance
  script:
    - aws s3 sync hk_client/dist s3://${S3_BUCKET}/staging
    - aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --paths "/index.html"

CLIENT__DEPLOY_PRODUCTION:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
  script:
    - aws s3 sync rose-client/dist s3://${S3_BUCKET}/production
    - aws cloudfront create-invalidation --distribution-id ${PRODUCTION_DISTRIBUTION_ID} --paths "/index.html"
