default:
  interruptible: true
  timeout: 1 hour

stages:
  - commit
  - deploy-staging

CLIENT_UNIT_TEST:
  image: node:20-alpine
  stage: commit
  script:
    - cd client
    - npm install
    - CI=true npm test
    
deploy-staging:
  image: node:20-alpine
  only:
    - main
  stage: deploy-staging
  script:
    - echo This is the deploy-staging stage

    