default:
  interruptible: true
  timeout: 1 hour

stages:
  - commit
  - acceptance
  - deploy-staging
  - deploy-production

CLIENT_UNIT_TEST:
  stage: commit
  script:
    - cd client
    - CI=true npm test

API_UNIT_TEST:
  stage: commit
  script:
    - echo Run unit tests for habit-kicker-rails

acceptance:
  stage: acceptance
  script:
    - echo This is the acceptance stage
    
deploy-staging:
  only:
    - main
  stage: deploy-staging
  script:
    - echo This is the deploy-staging stage

deploy-production:
  only:
    - main
  when: manual
  stage: deploy-production
  script:
    - echo This is the deploy-production stage
    