default:
  interruptible: true
  timeout: 30 minutes

stages:
  - commit

.client_setup: &client_setup
  image: node:20-alpine
  before_script:
    - cd hk_client
    - npm i

CLIENT_LINT:
  <<: *client_setup
  stage: commit
  script:
    - npm run lint

