version: '3.8'

services:
  nginx:
    build: nginx/.
    restart: always
    depends_on:
      - client
      - api
    ports:
      - '8080:80'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  client:
    build: client/.
    volumes:
      - /app/node_modules
      - ./client:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '5432:5432'

  api:
    build:
      context: habit-kicker-rails
      dockerfile: habit-kicker-rails/Dockerfile.CI

    depends_on:
      - postgres
    environment:
      - RAILS_DEVELOPMENT_HOSTS=api
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_HOST=postgres
    volumes:
      - ./habit-kicker-rails:/usr/src/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  cypress:
    build: acceptance_tests
    depends_on:
      nginx:
        condition: service_healthy
      api:
        condition: service_healthy
      client:
        condition: service_healthy