version: '3.8'

services:
  nginx:
    build: nginx/.
    restart: always
    depends_on:
      - client
      - api
    ports:
      - '8080:80'
  client:
    build: client/.
    volumes:
      - /app/node_modules
      - ./client:/app
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '5432:5432'

  api:
    build: habit-kicker-rails
    environment:
      - RAILS_DEVELOPMENT_HOSTS=api
      - DB_USER=postgres
      - DB_PASSWORD=postgres_password
      - DB_HOST=postgres
    volumes:
      - ./habit-kicker-rails:/usr/src/app

